### ISSUE TITLE
"Error 503 No healthy backends" 

### ISSUE THREAD

**Issue by wangjiahong666** [donnemartin/data-science-ipython-notebooks#33]
Hello, 

When I try to open the hyperlinks which should direct me to the correct ipython notebook, it returns me "Error 503 No healthy backends" 
"No healthy backends
Guru Mediation:
Details: cache-fra1236-FRA 1462794681 3780339426
Varnish cache server"

<img width="833" alt="capture" src="https://cloud.githubusercontent.com/assets/14320144/15112809/3e3a020c-15f9-11e6-9440-bfed7debac08.PNG">
<img width="350" alt="capture2" src="https://cloud.githubusercontent.com/assets/14320144/15112808/3e391b62-15f9-11e6-86b0-cf57a5d2e16e.PNG">

Thanks
Jiahong Wang

**Comment by donnemartin** [comment]
Hi Jiahong, 

Just checked, these are working for me.  

This is at the footer of the now-working nbviewer pages:

>Delivered by Fastly, Rendered by Rackspace

HTTP Error 503 - Service unavailable is likely from an outage from one of these services.

-Donne
