### ISSUE TITLE
Some of the links are giving 404 error

### ISSUE THREAD

**Issue by Lplenka** [donnemartin/data-science-ipython-notebooks#49]
I tried rnn-lstm in Keras, the link seems to be expired.
![image](https://user-images.githubusercontent.com/13533873/27465536-cc658728-57f1-11e7-81bf-9faf3cd0e246.jpg)

There are other many links too showing 404 error. Please fix them.

**Comment by donnemartin** [comment]
Hi @Lplenka thanks for reporting this issue, you're right the Keras notebook links are now broken.

**Comment by Zoltab1** [comment]
> I tried rnn-lstm in Keras, the link seems to be expired.
> ![image](https://user-images.githubusercontent.com/13533873/27465536-cc658728-57f1-11e7-81bf-9faf3cd0e246.jpg)
> 
> There are other many links too showing 404 error. Please fix them.
